apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-sample-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sriraj14/pythonsample-argo-deploy.git
    targetRevision: HEAD
    path: python-app
  destination: 
    server: https://kubernetes.default.svc
    namespace: python-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true