apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  selector:
    matchLabels:
      app: python-app
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: sriraj14/simplepython:1733a088acebe73f921eaa411736ee9a2aeafd68
          ports:
            - containerPort: 5000